# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: manager-config
  files:
  - controller_manager_config.yaml
