# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: flowconfig-daemon
  namespace: system
spec:
  template:
    metadata:
      labels:
        name: flowconfig-daemon
    spec:
      containers:
        - name: flowconfig-daemon
          securityContext:
            privileged: true
