apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    metadata:
      labels:
        name: flowconfig-daemon
    spec:
      containers:
        - name: flowconfig-daemon
          securityContext:
            privileged: true