# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: flowconfig-daemon
  namespace: system
  labels:
    control-plane: flowconfig-daemon
spec:
  template:
    metadata:
      labels:
        control-plane: flowconfig-daemon
    spec:
      containers:
      - command:
        - /flowconfig-daemon
        image: daemon-image:latest
        name: flowconfig-daemon
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      serviceAccountName: intel-ethernet-operator-controller-manager
      terminationGracePeriodSeconds: 10
