---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-cvl0-admin
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_cvl0_vfio
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-network",
  "trust": "on"
}'
