# permissions for end users to edit clusterflowconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterflowconfig-editor-role
rules:
- apiGroups:
  - flowconfig.intel.com
  resources:
  - clusterflowconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flowconfig.intel.com
  resources:
  - clusterflowconfigs/status
  verbs:
  - get
