# permissions for end users to edit devicepoolclusterpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devicepoolclusterpolicy-editor-role
rules:
- apiGroups:
  - ethernet.intel.com
  resources:
  - devicepoolclusterpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ethernet.intel.com
  resources:
  - devicepoolclusterpolicies/status
  verbs:
  - get
