# permissions for end users to view flowconfignodeagentdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flowconfignodeagentdeployment-viewer-role
rules:
- apiGroups:
  - flowconfig.intel.com
  resources:
  - flowconfignodeagentdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flowconfig.intel.com
  resources:
  - flowconfignodeagentdeployments/status
  verbs:
  - get
