# permissions for end users to edit nodeflowconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeflowconfig-editor-role
rules:
- apiGroups:
  - flowconfig.intel.com
  resources:
  - nodeflowconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flowconfig.intel.com
  resources:
  - nodeflowconfigs/status
  verbs:
  - get
