# permissions for end users to view nodeflowconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeflowconfig-viewer-role
rules:
- apiGroups:
  - flowconfig.intel.com
  resources:
  - nodeflowconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flowconfig.intel.com
  resources:
  - nodeflowconfigs/status
  verbs:
  - get
