# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - deployments/finalizers
  verbs:
  - '*'
- apiGroups:
  - ethernet.intel.com
  resources:
  - ethernetclusterconfigs
  - ethernetnodeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ethernet.intel.com
  resources:
  - ethernetclusterconfigs/finalizers
  - ethernetnodeconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - ethernet.intel.com
  resources:
  - ethernetclusterconfigs/status
  - ethernetnodeconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - machineconfigs
  verbs:
  - create
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - '*'
