
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ethernet.intel.com
  resources:
  - ethernetclusterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ethernet.intel.com
  resources:
  - ethernetclusterconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - ethernet.intel.com
  resources:
  - ethernetclusterconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - flowconfig.intel.com
  resources:
  - flowconfignodeagentdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flowconfig.intel.com
  resources:
  - flowconfignodeagentdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - flowconfig.intel.com
  resources:
  - flowconfignodeagentdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - flowconfig.intel.com
  resources:
  - nodeflowconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flowconfig.intel.com
  resources:
  - nodeflowconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - flowconfig.intel.com
  resources:
  - nodeflowconfigs/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flowconfig.intel.com
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - flowconfig.intel.com
  resources:
  - nodes/finalizers
  verbs:
  - update
- apiGroups:
  - flowconfig.intel.com
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
