
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - flowconfig.intel.com
  resources:
  - nodeflowconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flowconfig.intel.com
  resources:
  - nodeflowconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - flowconfig.intel.com
  resources:
  - nodeflowconfigs/status
  verbs:
  - get
  - patch
  - update
