apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    control-plane: flowconfig-daemon
  name: flowconfig-daemon-flowconfig-daemon
  namespace: intel-ethernet-operator-system
spec:
  selector:
    matchLabels:
      control-plane: flowconfig-daemon
  template:
    metadata:
      labels:
        control-plane: flowconfig-daemon
        name: flowconfig-daemon
    spec:
      containers:
      - command:
        - /flowconfig-daemon
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: flowconfig-daemon:0.0.1
        name: flowconfig-daemon
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/run/dcf/
          name: dcfsockdir
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - hostPath:
          path: /var/run/dcf/
        name: dcfsockdir
